# Generated by Django 5.1.2 on 2024-10-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_alter_review_reviewdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewDate",
            field=models.CharField(default="2024-10-20 15:57:56", max_length=19),
        ),
    ]
