# Generated by Django 5.1.1 on 2024-10-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_reviewdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.CharField(default='2024-10-21 09:24:01', max_length=19),
        ),
    ]
