# Generated by Django 5.1.1 on 2024-10-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_reviewdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.CharField(default='2024-10-22 10:09:33', max_length=19),
        ),
    ]
