# Generated by Django 5.1.2 on 2024-10-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0002_alter_order_orderdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderDate",
            field=models.CharField(default="2024-10-20 15:57:56", max_length=19),
        ),
    ]
