# Generated by Django 5.1 on 2024-10-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderAmount',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=10),
        ),
    ]
