# Generated by Django 5.1 on 2024-10-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_orderamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='product',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='numberOfView',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='userinterest',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_user_interest'),
        ),
    ]
