# Generated by Django 5.1.1 on 2024-11-12 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_categoryimage_product_shortdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(default='/categories/category_image.jfif', upload_to='categories/'),
        ),
    ]
