# Generated by Django 5.1.1 on 2024-11-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_orderstatus'),
        ('core', '0014_alter_review_order'),
    ]

    operations = [
    ]
