# Generated by Django 5.1 on 2024-11-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20241114_2052'),
        ('core', '0015_merge_20241114_2109'),
    ]

    operations = [
    ]
