# Generated by Django 5.1.2 on 2024-10-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0003_alter_payment_paymentdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paymentDate",
            field=models.CharField(default="2024-10-20 15:58:04", max_length=19),
        ),
    ]
