# Generated by Django 5.1.1 on 2024-10-22 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_userimage'),
        ('cart', '0002_remove_cart_customer_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
    ]
